name: deploy-runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          clean: false

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Set Environment Variables
        run: |
          export NG_ANALYTICS=false
          export TERM=xterm

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Deploy MURI to server path
        run: |
          sudo rm -rf /var/www/muri
          sudo mkdir -p /var/www/muri
          sudo cp -r dist/muri/browser/* /var/www/muri/
          sudo chown -R www-data:www-data /var/www/muri
          sudo chmod -R 755 /var/www/muri
          sudo systemctl reload nginx